name = "org-memo"
main = "src/server/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "org-memo-db"
database_id = "local"

[assets]
directory = "./dist/client"

[build]
command = "npm run build"
